// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PBCommon.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PBCommon {

  /// <summary>Holder for reflection information generated from PBCommon.proto</summary>
  public static partial class PBCommonReflection {

    #region Descriptor
    /// <summary>File descriptor for PBCommon.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PBCommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5QQkNvbW1vbi5wcm90bxIIUEJDb21tb24q1wEKEENsaWVudFRvU2VydmVy",
            "SUQSEgoOVENQX1VwX1VuS25vd24QABIQCgxUQ1BfUkVHSVNURVIQARINCglU",
            "Q1BfTE9HSU4QAhIVChFUQ1BfUkVRVUVTVF9NQVRDSBAKEhQKEFRDUF9DQU5D",
            "RUxfTUFUQ0gQCxIUChBVRFBfQkFUVExFX1JFQURZEDMSHAoYVURQX1VQX1BM",
            "QVlFUl9PUEVSQVRJT05TEDUSFwoTVURQX1VQX0RFTFRBX0ZSQU1FUxA3EhQK",
            "EFVEUF9VUF9HQU1FX09WRVIQOSqYAgoQU2VydmVyVG9DbGllbnRJRBIUChBU",
            "Q1BfRG93bl9Vbktub3duEAASGQoVVENQX1JFU1BPTlNFX1JFR0lTVEVSEAES",
            "FgoSVENQX1JFU1BPTlNFX0xPR0lOEAISHgoaVENQX1JFU1BPTlNFX1JFUVVF",
            "U1RfTUFUQ0gQChIdChlUQ1BfUkVTUE9OU0VfQ0FOQ0VMX01BVENIEAsSFAoQ",
            "VENQX0VOVEVSX0JBVFRMRRAyEhQKEFVEUF9CQVRUTEVfU1RBUlQQMxIdChlV",
            "RFBfRE9XTl9GUkFNRV9PUEVSQVRJT05TEDUSGQoVVURQX0RPV05fREVMVEFf",
            "RlJBTUVTEDcSFgoSVURQX0RPV05fR0FNRV9PVkVSEDkqOwoIR2FtZVR5cGUS",
            "DwoLR0FNRV9VTktPTlcQABIOCgpHQU1FX1R5cGUxEAESDgoKR0FNRV9UeXBl",
            "MhACQgJIA2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::PBCommon.ClientToServerID), typeof(global::PBCommon.ServerToClientID), typeof(global::PBCommon.GameType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ClientToServerID {
    [pbr::OriginalName("TCP_Up_UnKnown")] TcpUpUnKnown = 0,
    /// <summary>
    ///注册
    /// </summary>
    [pbr::OriginalName("TCP_REGISTER")] TcpRegister = 1,
    /// <summary>
    ///登录
    /// </summary>
    [pbr::OriginalName("TCP_LOGIN")] TcpLogin = 2,
    /// <summary>
    ///请求匹配
    /// </summary>
    [pbr::OriginalName("TCP_REQUEST_MATCH")] TcpRequestMatch = 10,
    /// <summary>
    ///取消匹配
    /// </summary>
    [pbr::OriginalName("TCP_CANCEL_MATCH")] TcpCancelMatch = 11,
    /// <summary>
    ///战斗准备
    /// </summary>
    [pbr::OriginalName("UDP_BATTLE_READY")] UdpBattleReady = 51,
    /// <summary>
    ///上传玩家操作
    /// </summary>
    [pbr::OriginalName("UDP_UP_PLAYER_OPERATIONS")] UdpUpPlayerOperations = 53,
    /// <summary>
    ///请求发送丢失帧数据
    /// </summary>
    [pbr::OriginalName("UDP_UP_DELTA_FRAMES")] UdpUpDeltaFrames = 55,
    /// <summary>
    ///游戏结束
    /// </summary>
    [pbr::OriginalName("UDP_UP_GAME_OVER")] UdpUpGameOver = 57,
  }

  public enum ServerToClientID {
    [pbr::OriginalName("TCP_Down_UnKnown")] TcpDownUnKnown = 0,
    /// <summary>
    ///注册
    /// </summary>
    [pbr::OriginalName("TCP_RESPONSE_REGISTER")] TcpResponseRegister = 1,
    /// <summary>
    ///登录反馈
    /// </summary>
    [pbr::OriginalName("TCP_RESPONSE_LOGIN")] TcpResponseLogin = 2,
    /// <summary>
    ///请求匹配反馈
    /// </summary>
    [pbr::OriginalName("TCP_RESPONSE_REQUEST_MATCH")] TcpResponseRequestMatch = 10,
    /// <summary>
    ///取消匹配反馈
    /// </summary>
    [pbr::OriginalName("TCP_RESPONSE_CANCEL_MATCH")] TcpResponseCancelMatch = 11,
    /// <summary>
    ///进入战斗
    /// </summary>
    [pbr::OriginalName("TCP_ENTER_BATTLE")] TcpEnterBattle = 50,
    /// <summary>
    ///开始战斗
    /// </summary>
    [pbr::OriginalName("UDP_BATTLE_START")] UdpBattleStart = 51,
    /// <summary>
    ///操作帧同步
    /// </summary>
    [pbr::OriginalName("UDP_DOWN_FRAME_OPERATIONS")] UdpDownFrameOperations = 53,
    /// <summary>
    ///丢失帧同步
    /// </summary>
    [pbr::OriginalName("UDP_DOWN_DELTA_FRAMES")] UdpDownDeltaFrames = 55,
    /// <summary>
    ///游戏结束
    /// </summary>
    [pbr::OriginalName("UDP_DOWN_GAME_OVER")] UdpDownGameOver = 57,
  }

  public enum GameType {
    [pbr::OriginalName("GAME_UNKONW")] GameUnkonw = 0,
    [pbr::OriginalName("GAME_Type1")] _1 = 1,
    [pbr::OriginalName("GAME_Type2")] _2 = 2,
  }

  #endregion

}

#endregion Designer generated code
