//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Chatpanel_prefab
    {
        public const string BundleName = "chatpanel_prefab";
        public const string CHATPANEL = "chatpanel";
    }
    public class Clientpanel_prefab
    {
        public const string BundleName = "clientpanel_prefab";
        public const string CLIENTPANEL = "clientpanel";
    }
    public class Loadingpanel_prefab
    {
        public const string BundleName = "loadingpanel_prefab";
        public const string LOADINGPANEL = "loadingpanel";
    }
    public class Lobbypanel_prefab
    {
        public const string BundleName = "lobbypanel_prefab";
        public const string LOBBYPANEL = "lobbypanel";
    }
    public class Massagepanel_prefab
    {
        public const string BundleName = "massagepanel_prefab";
        public const string MASSAGEPANEL = "massagepanel";
    }
    public class Netstatepanel_prefab
    {
        public const string BundleName = "netstatepanel_prefab";
        public const string NETSTATEPANEL = "netstatepanel";
    }
    public class Serverpanel_prefab
    {
        public const string BundleName = "serverpanel_prefab";
        public const string SERVERPANEL = "serverpanel";
    }
    public class Titlemassagepanel_prefab
    {
        public const string BundleName = "titlemassagepanel_prefab";
        public const string TITLEMASSAGEPANEL = "titlemassagepanel";
    }
}
