//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.HeNuoApp
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class ClientPanel
    {
        
        public const string NAME = "ClientPanel";
        
        [SerializeField()]
        public UnityEngine.UI.InputField InputField_Acc;
        
        [SerializeField()]
        public UnityEngine.UI.InputField InputField_Pass;
        
        [SerializeField()]
        public UnityEngine.UI.Button Button_Login;
        
        [SerializeField()]
        public UnityEngine.UI.Button Button_Register;
        
        private ClientPanelData mPrivateData = null;
        
        public ClientPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new ClientPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            InputField_Acc = null;
            InputField_Pass = null;
            Button_Login = null;
            Button_Register = null;
            mData = null;
        }
    }
}
