//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.HeNuoApp
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class MassagePanel
    {
        
        public const string NAME = "MassagePanel";
        
        [SerializeField()]
        public UnityEngine.UI.Text Info_Text;
        
        [SerializeField()]
        public UnityEngine.UI.Button Button_Conform;
        
        private MassagePanelData mPrivateData = null;
        
        public MassagePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new MassagePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            Info_Text = null;
            Button_Conform = null;
            mData = null;
        }
    }
}
