//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.HeNuoApp
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class MassagePanelData : QFramework.UIPanelData
    {
        public string info;
    }
    
    public partial class MassagePanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as MassagePanelData ?? new MassagePanelData();
            // please add init code here

            Info_Text.text = mData.info;

            Button_Conform.onClick.AddListener(() => { this.CloseSelf(); });
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
