//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.HeNuoApp
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class NetStatePanel
    {
        
        public const string NAME = "NetStatePanel";
        
        [SerializeField()]
        public UnityEngine.UI.Text Title_Text;
        
        private NetStatePanelData mPrivateData = null;
        
        public NetStatePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new NetStatePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            Title_Text = null;
            mData = null;
        }
    }
}
