//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.HeNuoApp
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class ServerPanel
    {
        
        public const string NAME = "ServerPanel";
        
        // 在线人数
        [SerializeField()]
        public UnityEngine.UI.Text OnlineCount;
        
        // 消息收发次数
        [SerializeField()]
        public UnityEngine.UI.Text MsgCount;
        
        [SerializeField()]
        public UnityEngine.UI.Button ServerStartOrStop;
        
        [SerializeField()]
        public UnityEngine.UI.Text StartOrStopText;

        [SerializeField()]
        public UnityEngine.UI.Text Text_IP;

        // 消息内容显示
        [SerializeField()]
        public UnityEngine.UI.Text MsgContent;
        
        private ServerPanelData mPrivateData = null;
        
        public ServerPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new ServerPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            OnlineCount = null;
            MsgCount = null;
            ServerStartOrStop = null;
            StartOrStopText = null;
            Text_IP = null;
            MsgContent = null;
            mData = null;
        }
    }
}
