//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.HeNuoApp
{
    using QF.Action;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class TitleMassagePanelData : QFramework.UIPanelData
    {
        public string info;
    }
    
    public partial class TitleMassagePanel : QFramework.UIPanel
    {

        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
 
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as TitleMassagePanelData ?? new TitleMassagePanelData();
            // please add init code here

            Title_Text.text = mData.info;

            this.Delay(5f, () => { this.CloseSelf(); });
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
