//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.HeNuoApp
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class LobbyPanel
    {
        
        public const string NAME = "LobbyPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Text Title_Text;
        
        [SerializeField()]
        public UnityEngine.UI.Text PlayerName_Text;
        
        [SerializeField()]
        public ScenePanel ScenePanel;
        
        [SerializeField()]
        public RectTransform SceneContent;
        
        [SerializeField()]
        public UnityEngine.UI.Button Button_CreateRoom;
        
        [SerializeField()]
        public UnityEngine.UI.InputField InputField_RoomCapacity;
        
        [SerializeField()]
        public UnityEngine.UI.InputField InputField_RoomName;
        
        [SerializeField()]
        public UnityEngine.UI.Text MsgContent;
        
        [SerializeField()]
        public UnityEngine.UI.InputField InputField_Msg;
        
        [SerializeField()]
        public UnityEngine.UI.Button Button_Send;
        
        private LobbyPanelData mPrivateData = null;
        
        public LobbyPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new LobbyPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            Title_Text = null;
            PlayerName_Text = null;
            ScenePanel = null;
            SceneContent = null;
            Button_CreateRoom = null;
            InputField_RoomCapacity = null;
            InputField_RoomName = null;
            MsgContent = null;
            InputField_Msg = null;
            Button_Send = null;
            mData = null;
        }
    }
}
